version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 25
    dupl:
      threshold: 150
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: ^(fmt\\.Print(|f|ln)|print|println)$
        - pattern: ^os\.(.*)$(# Using anything except Signal and SyscallError from the os package is forbidden )?
        - pattern: ^syscall\.[^A-Z_]+$(# Using anything except constants from the syscall package is forbidden )?
        - pattern: ^logrus\.Logger$
    funlen:
      lines: 80
      statements: 60
    goconst:
      min-len: 10
      min-occurrences: 4
  exclusions:
    generated: lax
    rules:
      - linters:
          - canonicalheader
          - cyclop
          - dupl
          - forcetypeassert
          - funlen
          - gocognit
          - lll
        path: _(test|gen)\.go
      - linters:
          - paralleltest
          - tparallel
        path: js\/modules\/k6\/http\/.*_test\.go
      - linters:
          - forbidigo
        text: use of `os\.(SyscallError|Signal|Interrupt)` forbidden
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
