name: Tests
permissions:
  contents: read
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: Build k6 with xk6 extension
        run: make build

      - name: Start LDAP container for tests
        uses: hoverkraft-tech/compose-action@ee6af68587292d72db67743171809c19787df4c9 # v3.1.0
        with:
          compose-file: "./test/compose.yaml"

      - name: Run tests
        run: |
          set -x
          go test ./...
